iOSユーザーに優しく
half-blue/A_plus_Tsukuba pull request #67
Opened 2022-12-04 16:40 UTC by nitoca

コピーリンクをクリックしたときのアラート追加。

2022-12-04 16:40 UTC, nitoca commented
あと、svg

2022-12-05 01:51 UTC, takumi1001 approved these changes
夜遅くにお疲れ様です。ローカルで動作確認しました。
問題ないと思います。

緑色のボタンのコピーアイコンを白色に変えてAndroidと統一したほうが（そういえば）きれいかなと思いましたが、こだわりとかありますか？

2022-12-05 07:57 UTC, nitoca commented
<img width="153" alt="スクリーンショット 2022-12-05 16 54 33" src="https://user-images.githubusercontent.com/78777225/205583239-1da16c64-400a-4136-93b3-be437856b2b5.png">
同意見です。統一感を出しました。ローカルでの確認は結構ですので、[変更箇所](https://github.com/half-blue/A_plus_Tsukuba/pull/67/commits/c782b72c1f68e549dda45499f13b2e00e5970ae7)だけ適切かどうか確認お願いします。

2022-12-05 09:13 UTC, takumi1001 requested changes
説明文のSVGとボタンのSVGが違うのはちょっと気持ち悪いのでは
もともとボタンのSVGの色を白に変えるほうがシンプルかと。

2022-12-05 09:16 UTC, takumi1001 commented
これでどうでしょうか

2022-12-05 10:29 UTC, nitoca commented
あざーーーーーーす！！
※確認済み

2022-12-05 10:29 UTC, merged