モーダルを利用した雑談スレッドへの遷移 (related issue #72)
half-blue/A_plus_Tsukuba pull request #73
Opened 2023-02-18 19:21 UTC by takumi1001

#72 に対応。

モーダル利用して雑談スレッドを見やすくしました。
@nitoca のブランチのデザインも参考にしています。
ローカルで動作OK.

以下スクショ
![image](https://user-images.githubusercontent.com/40143183/219884216-8618f982-a9b9-4128-b95f-053e29b92b4a.png)
![image](https://user-images.githubusercontent.com/40143183/219884231-1067ada9-0987-4ff1-8cb7-61f2a948a760.png)
![image](https://user-images.githubusercontent.com/40143183/219884247-42e4e5fa-3f6b-4857-bc9b-f86dd6a52c00.png)
![image](https://user-images.githubusercontent.com/40143183/219884260-32529fd2-214b-46a9-8af9-8f5b7b0a6bcd.png)

学園祭スレッドは隠してしまっています。やどさいのころに新入生スレッドの強調をやめて二つ並んで出せばいいかな。

2023-02-19 08:41 UTC, nitoca requested changes

2023-02-19 08:41 UTC, nitoca commented on board/templates/board/Search.html
> +            <a href="https://www.aplus-tsukuba.net/threads/6292/"
雑談スレッドへのリンクを絶対的なURLで指定しているのはなぜですか？

以下のリンクも同様

2023-02-19 08:49 UTC, takumi1001 commented on board/templates/board/Search.html
> +            <a href="https://www.aplus-tsukuba.net/threads/6292/"
確かにドメインに依存しないようにJinjaで埋め込んだほうがいいですね、後で直します。

完全に忘れてました。

2023-02-20 10:49 UTC, takumi1001 commented
@nitoca 修正したので再レビューお願いします．
同じページでそろっていないと変なので，
運営へのフィードバックスレッドへのリンクをただの相対リンクからDjangoの相対リンクになおしてます．

2023-02-22 10:04 UTC, nitoca approved these changes
確認しました。🫠

2023-02-22 10:36 UTC, merged